// Code generated by go awsdoublegen; DO NOT EDIT.
// This file was generated at 2020-01-29T21:22:05+11:00
package lambdadouble

import "github.com/aws/aws-sdk-go/aws/request"

var paginators = map[string]*request.Paginator{

	"ListAliases": &request.Paginator{
		InputTokens:     []string{"Marker"},
		OutputTokens:    []string{"NextMarker"},
		LimitToken:      "MaxItems",
		TruncationToken: "",
	},

	"ListEventSourceMappings": &request.Paginator{
		InputTokens:     []string{"Marker"},
		OutputTokens:    []string{"NextMarker"},
		LimitToken:      "MaxItems",
		TruncationToken: "",
	},

	"ListFunctionEventInvokeConfigs": &request.Paginator{
		InputTokens:     []string{"Marker"},
		OutputTokens:    []string{"NextMarker"},
		LimitToken:      "MaxItems",
		TruncationToken: "",
	},

	"ListFunctions": &request.Paginator{
		InputTokens:     []string{"Marker"},
		OutputTokens:    []string{"NextMarker"},
		LimitToken:      "MaxItems",
		TruncationToken: "",
	},

	"ListLayerVersions": &request.Paginator{
		InputTokens:     []string{"Marker"},
		OutputTokens:    []string{"NextMarker"},
		LimitToken:      "MaxItems",
		TruncationToken: "",
	},

	"ListLayers": &request.Paginator{
		InputTokens:     []string{"Marker"},
		OutputTokens:    []string{"NextMarker"},
		LimitToken:      "MaxItems",
		TruncationToken: "",
	},

	"ListProvisionedConcurrencyConfigs": &request.Paginator{
		InputTokens:     []string{"Marker"},
		OutputTokens:    []string{"NextMarker"},
		LimitToken:      "MaxItems",
		TruncationToken: "",
	},

	"ListVersionsByFunction": &request.Paginator{
		InputTokens:     []string{"Marker"},
		OutputTokens:    []string{"NextMarker"},
		LimitToken:      "MaxItems",
		TruncationToken: "",
	},
}
