// Code generated by go awsdoublegen; DO NOT EDIT.
// This file was generated at 2020-01-29T21:22:05+11:00
// For SDKVersion 1.28.13
//Package pricingdouble contains test double implementation of pricingiface.PricingAPI
package pricingdouble

//go:generate go run -tags doublegen ../../awsdoublegen/cmd/services/pricing.go
